### ISSUE TITLE
Velcro.Runtime package out of date?

### ISSUE THREAD

**Issue by alexswan10k** [ggoodman/velcro#17]
Hi,

Just trying to assemble the bundler for a project alongside the runtime (using the published npm packages), but I am hitting a few bumps with respect to their being inconsistencies between the expected resolverHost for @velcro/runtime and the actual resolverHost in @velcro/resolver-host-compound. (isCacheable seems to be missing in newer).

Looking at the versions, it does appear that @velcro/runtime is the only package that hasn't been updated, so perhaps the types are just out of sync and the core runtime needs releasing? If not perhaps I am assembling these packages incorrectly, in which case perhaps you could point me in the right direction?

While I am at it, I am also not 100% sure what the best approach is for substituting real packages with the runtime.

Currently I am doing something along the lines of:

`
  const memoryHost = new Velcro.ResolverHostMemory(
    initialFiles,
    "compound_host_with_cache"
  );
  const resolverHostUnpkg = new VelcroResolverHostUnpkg.ResolverHostUnpkg();
  const resolverHost = new VelcroResolverHostCompound.ResolverHostCompound({
    "https://unpkg.com/": resolverHostUnpkg as any,
    [memoryHost.urlFromPath("/").href]: memoryHost
  });

const runtime = Velcro.createRuntime({
    cache: _cache,
    injectGlobal: Velcro.injectGlobalFromUnpkg,
    resolveBareModule: async (a, b, name, d) => {
      if (name === "react") return memoryHost.urlFromPath("/react").href;
      if (name === "react-dom")
        return memoryHost.urlFromPath("/react-dom").href;
      if (name === "prop-types")
        return memoryHost.urlFromPath("/prop-types").href;
  

      const res = await Velcro.resolveBareModuleToUnpkg(a, b, name, d);
      return res;
    },
    resolverHost, 
    rules: [
       ...
        ]
      }

    ]
  });
`

And then after assembling, I can do the following:

`
  runtime.set(memoryHost.urlFromPath("/react").href, React);
  runtime.set(memoryHost.urlFromPath("/react-dom").href, ReactDom);
`

Although this might work, it doesn't seem to be consistent with the bundler api, and also it doesn't work for underlying webpack plugins like css-loader or style-loader. It would be nice to do this because stuff like sass-loader has tons of dependencies and is slow on first pass.

Any thoughts?

**Comment by ggoodman** [comment]
Hi @alexswan10k, you're right that the runtime package has been left behind. I spent some time shifting focus from build-on-demand to build ahead-of-time.

Can you tell me more about your use-case?

**Comment by alexswan10k** [comment]
Sure.

Its probably easier if I just show you:

This is a [sample](https://app.leansquad.co.uk/b701d9b0-004b-4462-83f5-43aa86502b31/476347052/jp/edit/0c784eef-670d-4aeb-837a-477d707a1226?) from our RAD platform, showing an inline component system I am working on.

Obviously for a production use case, it would be necessary to have some kind of bundling system for this, but the runtime resolution works brilliantly for development, and also benefits from caching common resources etc. It would be nice to get both running side by side if possible.

The constraint for me is that the component is already executed in a react runtime where certain packages already exist from a webpack bundle. I am feeding these into the velcro loader so they don't load twice.

Just FYI there seem to be intermittent issues with cors headers being thrown out, so try refresh a few times if your having trouble seeing anything.. Seems to work after 3! I will look into that.

**Comment by ggoodman** [comment]
Hrm, fascinating. While this isn't the primary use-case I'd envisioned for Velcro, it is certainly something that _should_ be possible.

The challenge for me right now is that I'm not quite ready to invest more time in building out loaders and doubling down on the Webpack ecosystem. I've actually been hacking away at a much _faster_ resolver / bundler since my main effort will probably be in that direction.

Do you want to take a stab at getting the Runtime back up to date?

**Comment by alexswan10k** [comment]
Yeah sure happy to take a look. Quite a few plates spinning atm, but hould find some time in the next few days :)

Il let you know.

**Comment by alexswan10k** [comment]
Ok, I have had a chance to have a bit of a dig around in the codebase, and I am not entirely sure where to start. I am just going to dump my consciousness stream if you don't mind, and hopefully you can can fill me in.

Firstly - it looks like the actual runtime package was removed completely, but if I understand correctly the bundler seems to now contain a bunch of classes which take the place of these. It seems to me like there are a bunch of concepts (assets for example) that would have to be shared between bundler and runtime? What would be your first step here, restore the existing package and go from there?

Also, I noticed there is actually a runtime.js with a runtime.d.ts which seems to look similar to the original runtime, although i'm not sure the interface is the same any more. These don't appear to be immediately used in the demo, although hacking around i did manage to get a reference to some concept called runtime.

To understand the bundler better I had a dig around in the tests, which mostly make sense for how to consume the interface. The problem is the tests seem to be written against an older interface of the bundler, and all fail on my machine. I had a go at fixing them (entrypoints is now a string rather than { type: string, href: string}[] ), but was still getting " Unable to resolve ''" inside resolveBareModuleReference. 


Going back to my original problem (in the context of bundling), it does look like my approach of using a memoryresolver to ignore certain assets would work with the bundler. The problem I am struggling with is precisely how require calls are propagated through the final bundle. I noticed there is a factory with a require parameter, where require calls are not rewritten like webpack. I assume there is some function passed through that has acts as some kind of local package repository or dictionary to object lookup.

What I ultimately want to do is at runtime redirect some require calls to point at arbitrary objects (not code files) I specify - `{ 'react' : MyExternalReactInstance, 'react-dom': MyExternalReactDomInstance ...etc }`. Ideally I would also like for them not to end up in the bundle.

**Comment by ggoodman** [comment]
Maybe you would like to collaborate with me on the work I've been doing in the rewrite. A second use-case will help inform the design.

I've pushed this WIP to the `resolver2` branch and all relevant code is within the `./packages/resolver2` directory for now.

Here is the gist...

## Resolver strategies

I renamed `ResolverHost` to `ResolverStrategy`. A `ResolverStrategy` implements an interface that allows a `Resolver` to leverage it to resolve requested urls to found urls.

## Resolver contexts

The first argument to each method of the `ResolverStrategy` is now a `ResolverContext`. The `ResolverContext` is an object that allows strategies to resolve / read files themselves. The `ResolverContext` now holds the logic to deduplicate in-flight operations and does in-memory caching of resolution operations.

The same context (or children thereof) should be used for the duration of a logical session where you want predictable and consistent resolution results.

## Bundling

Bundling is a multi-step process that involves:

1. Creating a graph via a `buildGraph` function.
2. Breaking up the resulting graph into a set of chunk(s) (by default there is a single chunk)
2. Converting each chunk into a usable representation. For now, the only representation is a format suitable for including in a page's `script` tag.
3. Consuming the resulting chunks. A 'runtime' is what understands the output representation and is able to wire up modules and execute them.

### Building a graph

This takes some entrypoints, an optional `process.env.NODE_ENV` value and a `Resolver:

https://github.com/ggoodman/velcro/blob/2540897dac2c3ba904b22f5142fbbde62430280c/packages/resolver2/src/graph/graphBuilder.ts#L26-L39

### Breaking up the graph into chunks

Right now, this is hard-coded to produce an array with a single `Chunk` in it:

https://github.com/ggoodman/velcro/blob/2540897dac2c3ba904b22f5142fbbde62430280c/packages/resolver2/src/graph/graph.ts#L38-L46

### Converting a chunk into code

This will wrap all `SourceModule`s in the chunk in some boilerplate, concatenate them all and then append the 'runtime':

https://github.com/ggoodman/velcro/blob/2540897dac2c3ba904b22f5142fbbde62430280c/packages/resolver2/src/build/chunk.ts#L47-L99

The `createRuntime` function is designed so that it can be stringified (via `.toString()`). In other words, it takes no dependencies outside its function body, except arguments. It contains a pseudo `Module` implementation and a `Runtime` class that knows how to orchestrate modules defined in a `VelcroStaticRuntime` object (such as the one passed in).

https://github.com/ggoodman/velcro/blob/2540897dac2c3ba904b22f5142fbbde62430280c/packages/resolver2/src/runtime/runtime.js#L13-L136

### Consuming the resulting chunks

The result of all of the above is a string, which, when written to a file looks like this: https://raw.githubusercontent.com/ggoodman/velcro/resolver2/packages/resolver2/test_chunk.js.

That file can be loaded in node and executed like this:

```
Welcome to Node.js v12.16.3.
Type ".help" for more information.
> require('./test_chunk');
{}
> Velcro.runtime.require('file:///index.js');
{
  Avatar: {
    '$$typeof': Symbol(react.forward_ref),
    render: [Function: Avatar],
    propTypes: { src: [Function: bound checkType], size: [Function] },
    defaultProps: {}
  },
  // Lots of lines of `react-ui` exports
}
```

The whole flow can be seen in its, raw, half-functional glory here: 

https://github.com/ggoodman/velcro/blob/2540897dac2c3ba904b22f5142fbbde62430280c/packages/resolver2/test.ts#L40-L84

**Comment by ggoodman** [comment]
I think your use-case where you want to override specific requires could be achieved by the new, optional `getUrlForBareModule` method.

https://github.com/ggoodman/velcro/blob/2540897dac2c3ba904b22f5142fbbde62430280c/packages/resolver2/src/strategy.ts#L42-L48

You could create a `ResolverStrategy` that, in general, is a pass-through to the `CdnResolverStrategy` (ie unpkg / jsdelivr). But when certain bare module requests come through you respond with a url of your picking.

This custom url might point to a `file:///` url, for example, or to something in a custom `ResolverStrategy` that you write for these application-specific modules.

**Comment by alexswan10k** [comment]
Thanks for taking the time to reply, that helped a lot.

Yes I think your right, the file substitution is similar to what I am doing currently with the old runtime, but the extra piece here may be that an external 'require' function is then called to get the external object.

so for example a placeholder file that might be injected
```
//file:///react.js
export default window.externalRequire("react");
```


When dynamically executing the bundle, I could define externalRequire somewhere, to inject external dependencies:
```
import * as React from "react; //webpack resolves these at my app's build time
import * as package1 from "package1" 

let deps = new Map({
    "react": React,
    "package1": package1 
...etc
});
window.externalRequire = (name) => deps.get(name);

```

Now obviously global refs are bad, and perhaps it may be more desirable if the bundle could be executed in the context of some scope where this could all be defined, although this isn't technically necessary for my basic use case.

It has just got me thinking about all sorts of other ways this could be used in my specific case to centralise common dependencies by feeding them through from other bundles in this way. One thing I am patently aware of is the potential repetition that will occur if i have 5 inline components all sharing the same base packages, hence initially looking at dynamic loading.


One thing that I did note is the output bundle actually contains a sort of manifest of the cdn locations of the requested files. I wonder if another way to reintroduce the cdn runtime resolution would be to simply omit the actual code, and use the manifest in the runtime to resolve it on demand. Although this would be slower, the benefit is that your 'bundle'/bootstrapper would be tiny, and all the benefits of cdns (caching/geo etc) could be utilised. I get that this totally defeats the object of bundling mind, but perhaps this is another path to being able to utilise a cdn directly in production.

**Comment by ggoodman** [comment]
I was actually thinking more along the lines of:

```js
//file:///react.js
module.exports = require("react");
```

Then, instead of using the `CdnStrategy` directly, you would instead wrap it in a sort of pass-through strategy that will only hook into the `getUrlForBareModule` operation.

For that method, you could have it be:

```js
class MyCustomModuleStrategy extends AbstractResolverStrategy {
  constructor(childStrategy) {
    this.childStrategy = childStrategy;
  }

  // Example pass-through method
  getCanonicalUrl(ctx, uri) {
    return this.childStrategy.getCanonicalUrl(ctx, uri);
  }

  // Example to override react
  getUrlForBareModule(ctx, name, spec, path) {
    if (name === 'react') {
      return {
        found: true,
        uri: Uri.parse(`myapp:///${name}@${spec}${path}`),
      };
    }
 
    // Let other bare modules get handled by the CdnStrategy (the child strategy)
    if (this.childStrategy.getUrlForBareModule) {
      return this.childStrategy.getUrlForBareModule(ctx, name, spec, path);
    }
  }
}
```

Then, you would need _another_ custom strategy that is able to resolve `myapp://`.

**Comment by ggoodman** [comment]
Or are you looking to bring logic that already exists in the _environment_ into the context of code running via Velcro? Ie: inject the `react` already exposed in the context into the Velcro world?

**Comment by ggoodman** [comment]
If that is the case a `velco.inject(moduleId, moduleInst)` method on the runtime might be a clean solution.

**Comment by alexswan10k** [comment]
Yeah you got it. I need the actual runtime reference, not the code as such. The webpack bundle already has done that bit for me. 

That sounds like it might work. I assume I would still need a strategy to tell the resolver to ignore certain file paths?

It looks like i'm doing something close to this with the old runtime:
```
runtime.set(memoryHost.urlFromPath("/react").href, React);
```

**Comment by ggoodman** [comment]
That's a really good point. I think the cleanest way to do it would still be a custom pass-through `ResolverStrategy` but at this point the whole thing is missing support for 'late bound' dependencies.

In other words, I think bundling would fail if react was expected to only be injected at runtime.

Maybe the approach taken by Rollup's [external option](https://rollupjs.org/guide/en/#external) could be used as inspiration. You can have set `external` as a function whose job is to indicate whether a given dependency should be treated as 'external' or not.

**Comment by ggoodman** [comment]
Here's what I'm thinking for the `external` option:

https://github.com/ggoodman/velcro/blob/732c5070dcc559aaa02c8901eb09651f9428b9fe/packages/resolver2/src/graph/graphBuilder.ts#L33-L56

And for the `velcro.inject`:

https://github.com/ggoodman/velcro/blob/732c5070dcc559aaa02c8901eb09651f9428b9fe/packages/resolver2/src/runtime/runtime.js#L105-L118

**Comment by alexswan10k** [comment]
I like it.

I think the first trick of having a placeholder file with a function call to extrequire would technically work (the rest of the dep subgraph would not be traversed because the placeholder file does not have any dependencies), but having externals as a first class concept is a far better solution. It is also more intuitive to a consumer of the api what is actually happening.

Do you need any help to make this happen?

**Comment by ggoodman** [comment]
I just pushed support for (optionally) generating source maps.

**Comment by ggoodman** [comment]
I think this very well do exactly what you're looking for: https://github.com/ggoodman/velcro/blob/fe412d16133facdd254c5e98d634d5699143725f/packages/resolver2/src/execute.ts#L13-L69

Example using it to load `react@13.16.x` out of 'thin air':

https://github.com/ggoodman/velcro/blob/fe412d16133facdd254c5e98d634d5699143725f/packages/resolver2/test.ts#L87-L92

**Comment by ggoodman** [comment]
I will probably rename the `execute` method to something a bit less generic, but pretty excited by how this composes.

**Comment by ggoodman** [comment]
Here is a concrete example of what I think you're trying to achieve: https://plnkr.co/edit/sDnzv3QEv6wudM9P

**Comment by alexswan10k** [comment]
I cant actually get your sample to work - it seems to be trying to resolve a file:///index.js and i cant work out where from.

I get what you are doing though. That is super cool :)

On a side note with respect to the external function. Would you ever envisage a scenario where that does something independent of injected modules? It seems that if that's not the case, the function could derive its behaviour entirely from working out if the module name is a key in the injected modules list (and thus be internal to the runner).

Loving that you can use other cdns as well, i didn't even realise that was possible. I am also trying to work out what the guys at bit.dev are doing - apparently they are also working on exposing their component packages/bundles over CDN's, so will try and find out if that can all play nicely with the velcro ecosytem. Nice, this is all pretty exciting though.

**Comment by ggoodman** [comment]
Can you share details of the issue you are seeing? I can't reproduce it.

**Comment by alexswan10k** [comment]
```
velcro.js:1 Uncaught (in promise) W: Graph building failed with errors:
No such directory file:/// at
 GraphBuilder.doAddUnresolvedUri:file:///index.js
    at Ar.buildGraph (https://run.plnkr.co/preview/cka6w8uox00073b6e2celqvo0/lib/velcro.js:1:176303)
    at async Object.e.execute (https://run.plnkr.co/preview/cka6w8uox00073b6e2celqvo0/lib/velcro.js:1:224134)
```

**Comment by alexswan10k** [comment]
Awesome. Will have a crack at getting this integrated next week.

Thanks again, really appreciate the work your doing 👍

**Comment by alexswan10k** [comment]
Not sure where best to follow up so guess here is as good as any.

I have had a go at trying to hook all this up, with little avail unfortunately. I keep hitting the same error as seen on the sandbox, after having tried various combinations of the new runner or composing these constructs myself.

I am pretty sure I have narrowed it down to the listEntries first line in memoryStrategy.ts

The offending line:
```
Uri.ensureTrailingSlash(uri).fsPath
```
where fsPath seems to be returning a backslash rather than a forward slash, which is then fed into getEntryAtPath, which then resolves a parent as undefined, as no segment/child can be found matching "\\" obviously! 

I cant seem to locate fsPath on Uri or the builtin URL prototype, so perhaps you can help me work out where this is coming from?

I also noticed an inconsistency between ```Uri.parse('memory:///')``` and the generated ```Uri("memory:/directory/path")```. Not sure if this is a problem though, i just cant rule it out yet either.

**Comment by ggoodman** [comment]
Can you open a new issue for this? I suspect that it has to do with the way the Uri class I'm using tries to adapt to the host's path separator character.

In the issue can you confirm what the environment looks like in which you are running your tests?
