### ISSUE TITLE
Support for non-js and non-json files

### ISSUE THREAD

**Issue by ggoodman** [ggoodman/velcro#23]
@alexswan10k you were asking about the possibility of including files other than `.js` and `.json` in Velcro.

This is something I do want to support but having tried the webpack loader approach in the past, I'm not sure that I want to go that route again. Webpack's loader ecosystem is heavily invested in a world where access to the file-system is taken for granted, which conflicts with Velcro's philosophical direction.

I think an approach we can consider right now is providing a mechanism to inject different _Parser_s.

There is already a layer of indirection where we could support pluggable parser plugins: https://github.com/ggoodman/velcro/blob/b54196f4eb78617d5eeb71441d7aeec33810e4c9/packages/%40velcro/bundler/src/graph/graphBuilder.ts#L344-L357

Right now, the contract is that any transformations of the underlying files need to be passed back to Velcro as arrays of `CodeChange`s:

https://github.com/ggoodman/velcro/blob/b54196f4eb78617d5eeb71441d7aeec33810e4c9/packages/%40velcro/bundler/src/graph/parsing.ts#L21-L37

I'm not convinced that this is an approach that will continue to meet the different objectives of Velcro. I had decided to make the code changes raw json so that, for example, parsing could be delegated to a `Worker`. I think that's probably a useful constraint to keep in mind: the contract between a parser plugin and Velcro's bundler should be encodable in JSON.

My current thinking is along the lines below. There should be a conceptual difference between parsing and generating.

- parsers: something that takes raw content and produces dependencies and basic transforms to produce an intermediate format.
- generators (straw-man name): something that understands the intermediate format and is able to produce code in the desired target format (such as CommonJS, like we do now).

I don't know what the intermediate format should be. For example, Rollup uses ESM but that means introducing a CJS -> ESM transform which is quite a project in itself.

**Comment by alexswan10k** [comment]
Been trying to consolidate my thoughts around this one, bear with me.

Firstly its probably worth fussing over the terminology 'parser', as i'm not sure it accurately describes whats happening. A parser generally is just about taking text and turning it into a list or tree of tokens which are then available for further transforms. What you are doing here is kind of beyond that, in that your defining a list of operations to perform on the text in a subsequent pipeline/interpreter. By the way I have no problem with JSON. I write F# all day so passing around data is all I know :)

I wanted to quickly go over the webpack ecosystem, as I think there are some important points to bear in mind, whatever direction we go.

* Loaders can be chained to make pipelines (the output of 1 is fed into the input of another). You see a lot of this in css, allowing composition and max reuse. The style-loader for example is often composed with the css-loader, or sass-loader, or any other arbitrary css generating pipeline.
* Some loaders have DOM side effects - the style-loader for example injects stuff into style tags into the dom.
* Loaders can call whole transform engines to operate on the file (babel, scss, typescript etc).
* Loaders can arbitrarily be called anywhere in any fashion, with the explicit !!loader syntax. This is pretty rare in packages but worth being aware of.
* The css-loader can load css modules, which are basically objects which you can reference (as seen here)[https://www.jackfranklin.co.uk/blog/css-modules-webpack-react/]
* I have seen packages importing binary files like images, fonts etc.
* The ecosystem is huge, everything from template loaders to linters to language transforms.

I would love to do a side-by-side with rollup but I am not that familiar with it, perhaps you have a better idea of how this overlays?

Now I am not suggesting that the loader ecosystem is the answer, but I also want to highlight the reality that mirroring all this is a non trivial endeavour. The problem is that many people are using existing tools like rollup, webpack, browserify etc, and therefore you can guarantee someone has done something crazy in a package somewhere that depends on this, and its just a question of time before we get burned. 

I think its also fair to say that a lot of loaders are only really used for top level projects, but i can attest to the fact that people are definitely using both css approaches mentioned above in their packages. 

##### Some thoughts on where to go from here
It is my opinion that we probably need the following:

* Parsers/loaders need to be pluggable (a simple ```{ suffix: string, loader: FileCtx => Promise<FileCtx> }``` would probably suffice for 95% of cases. (where filectx is something like what you got now - ```{ text: string, type: string, metadata: ... }```). I imagine FileCtx also cannot contain an AST, because any AST would need to be language agnostic. This also reduces the bundle size allowing people to eventually plug any crazy thing they want in.
* Parsers/loaders really need to be composable so you can form pipelines (but you get that for free if your interface is just an identity function).

I get the frustration with workers btw, I come from a world where I can just Task.StartNew (function) and I have a new thread (technically its a task but semantics heh). It doesn't look like there are any half decent libraries to help marshal functions across worker boundaries either, so every time you have to do it is a massive ballache. One thing that I would mention though, is that really you almost want to throw all bundling work over to a worker. Doing just the transforms seems like only half the potential gain, no?
